baseURL = "https://subhAShita.github.io/"
languageCode = "en-us"
title = "सुभाषित-सङ्ग्रहः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/subhAShita/subhAShita.github.io/edit/content/"
  contactLink = "https://github.com/subhAShita/subhAShita.github.io/issues/new"
  build_img = "https://github.com/subhAShita/subhAShita.github.io/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/subhAShita/subhAShita.github.io/actions/workflows/build.yml"
  env = "production"  
  # disqusShortcode = "subhashita-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true


[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2
